language: julia
os:
    - linux
    - osx
julia:
    # - release # definitions of Tuples are not compliant with Julia -0.3 
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("MLBase");  Pkg.test("MLBase")'